name: GitHub Pages Staging

on:
  push:
    branches:
      - main
      - ci
    tags:
      - 'v*.*.*-*'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip Folder
        run: cd media && cp ../LICENSE ./ && zip -r "ENS Media Kit.zip" . && mv "ENS Media Kit.zip" ../

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: "ENS Media Kit.zip"
          generate_release_notes: true
          body: |
            This is a pre-release of the ENS Media Kit. To download the assets see the "Assets" dropdown below. There you will find archive file containing the media-kit.
