name: GitHub Pages Staging

on:
  push:
    branches:
      - main
      - ci
    tags:
      - 'v*.*.*-*'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip Folder
        run: zip -r ENS\ Media\ Kit.zip .

      - uses: actions/upload-artifact@v3
        with:
          name: media-kit
          path: ENS\ Media\ Kit.zip
